import type { Metadata } from "next";
import { SITE_NAME, SITE_URL } from "@/lib/site";

/**
 * Per-page metadata. Every page sets its own canonical, og:url and social
 * titles here because Next.js merges metadata shallowly: a nested object set
 * in the root layout (alternates, openGraph) is inherited whole by every page
 * that doesn't set its own. That is how every page once declared the homepage
 * as its canonical.
 *
 * The social card is generated by src/app/opengraph-image.tsx, but it must be
 * referenced here too: a page that sets its own openGraph/twitter object
 * replaces the one the root image file would otherwise supply.
 */
const SOCIAL_IMAGE = {
  width: 1200,
  height: 630,
  alt: `${SITE_NAME}: marketing that earns trust, then keeps it.`,
};

export function pageMetadata({
  title,
  description,
  path,
  noindex = false,
  image,
  article,
}: {
  /** Page title without the brand; omit on the homepage. */
  title?: string;
  description: string;
  /** Route path beginning with "/", resolved against metadataBase. */
  path: string;
  /** Keep the page crawlable but out of search results. */
  noindex?: boolean;
  /** The page's own picture for social cards (a blog post's header), in place of the shared card. */
  image?: { src: string; width: number; height: number; alt: string };
  /** Marks the page as an article, with its real publish and edit times. */
  article?: { published: string; modified: string };
}): Metadata {
  // Dash, not pipe: Google rewrites pipe separators about twice as often
  // (Zyppy title-rewrite study). Brand last so the page topic leads.
  const fullTitle = title ? `${title} - ${SITE_NAME}` : `${SITE_NAME} - Brand, Web and Growth`;

  const social = (shared: string) =>
    image
      ? [{ url: image.src, width: image.width, height: image.height, alt: image.alt || fullTitle }]
      : [{ url: shared, ...SOCIAL_IMAGE }];

  return {
    title: { absolute: fullTitle },
    description,
    alternates: { canonical: path },
    openGraph: {
      ...(article
        ? { type: "article", publishedTime: article.published, modifiedTime: article.modified }
        : { type: "website" }),
      siteName: SITE_NAME,
      locale: "en_US",
      url: path,
      title: fullTitle,
      description,
      images: social("/opengraph-image"),
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: social("/twitter-image"),
    },
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
  };
}

/** BreadcrumbList JSON-LD from [name, path] pairs, root first. */
export function breadcrumbJsonLd(items: [name: string, path: string][]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map(([name, path], i) => ({
      "@type": "ListItem",
      position: i + 1,
      name,
      item: `${SITE_URL}${path === "/" ? "" : path}`,
    })),
  };
}
