import type { Metadata } from "next";
import { SITE_NAME } from "@/lib/site";

/**
 * Per-page metadata. Every page sets its own canonical, og:url and social
 * titles here because Next.js merges metadata shallowly: a nested object set
 * in the root layout (alternates, openGraph) is inherited whole by every page
 * that doesn't set its own. That is how every page once declared the homepage
 * as its canonical.
 *
 * The social card is generated by src/app/opengraph-image.tsx, but it must be
 * referenced here too: a page that sets its own openGraph/twitter object
 * replaces the one the root image file would otherwise supply.
 */
const SOCIAL_IMAGE = {
  width: 1200,
  height: 630,
  alt: `${SITE_NAME}: marketing that earns trust, then keeps it.`,
};

export function pageMetadata({
  title,
  description,
  path,
  noindex = false,
}: {
  /** Page title without the brand; omit on the homepage. */
  title?: string;
  description: string;
  /** Route path beginning with "/", resolved against metadataBase. */
  path: string;
  /** Keep the page crawlable but out of search results. */
  noindex?: boolean;
}): Metadata {
  // Dash, not pipe: Google rewrites pipe separators about twice as often
  // (Zyppy title-rewrite study). Brand last so the page topic leads.
  const fullTitle = title ? `${title} - ${SITE_NAME}` : `${SITE_NAME} - Brand, Web and Growth`;

  return {
    title: { absolute: fullTitle },
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: "en_US",
      url: path,
      title: fullTitle,
      description,
      images: [{ url: "/opengraph-image", ...SOCIAL_IMAGE }],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [{ url: "/twitter-image", ...SOCIAL_IMAGE }],
    },
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
  };
}
